// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Stat {
    /**
     * Creates a new Stat instance.
     * @param {Partial<Stat>} [$$source = {}] - The source object to create the Stat.
     */
    constructor($$source = {}) {
        if (!("xp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["xp"] = 0;
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["level"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stat(/** @type {Partial<Stat>} */($$parsedSource));
    }
}
