// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotificationService handles system notifications
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * ShowNotification displays a system notification
 * @param {string} title
 * @param {string} message
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ShowNotification(title, message) {
    let $resultPromise = /** @type {any} */($Call.ByID(2666014592, title, message));
    return $resultPromise;
}
